config/routes.rb
SFD2013::Application.routes.draw do

  get "events/full", :as => "event_is_full"
  get '/feed' => 'events#feed',
  :as => :feed,
  :defaults => { :format => 'atom' }

  get "home/index"
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root to: 'home#index'
  resources :users, only: [:create]

  get "events/:id/register", :to => "participants#new", :as => "registeration"
  post "events/:id/register", :to => "participants#create", :as => "registeration_post"
  get "events", :to => "events#index"
  get "events/:id", :to => "events#show", :as => "event"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/event.rb
require 'date'


class Event < ActiveRecord::Base
  validates :name, :presence => true
  validates :description, :presence => true
  validates :datetime, :presence => true

  has_many :media
  has_many :participants
  has_many :resources

  def self.future
    self.where(["datetime > ?", DateTime.now()]).order('datetime')
  end

  def self.past
    self.where(["datetime < ?", DateTime.now()])
  end

  def finished?
    self.datetime < DateTime.now
  end

  def is_full?
    if self.capacity == 0
      true
    else
      false
    end
  end
end

app/models/media.rb
class Media < ActiveRecord::Base
  belongs_to :event

  has_attached_file :file, :styles => {
    :original => "1025x800>",
    :medium => "200x200>",
    :thumb => "100x100>" },
  :url => "/assets/gallery/:class/:attachment/:style/:filename",
  :path => ":rails_root/public/assets/gallery/:class/:attachment/:style/:filename"


  validates :file, :attachment_presence => true
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :email, :email_format => {:message => _('is not looking good')}
  validates :event_id, :presence => true

  belongs_to :event

end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :event
  validates :name, :presence => true
  validates :url, :presence => true
  validates :event_id, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base

  before_save do
    self.email = email.downcase
  end

  validates :email, :email_format => {:message => _('is not looking good')}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
require "persian_string"


class EventsController < ApplicationController

  def index
    @future_events = Event.order("datetime DESC").future.limit(100)
    @past_events = Event.order("datetime ASC").past.limit(100).reverse
  end

  def full
  end

  def show
    @event = Event.find(params[:id])
    @reverse_dir = "ltr"
    if I18n.locale == :fa
      @reverse_dir = "rtl"
    end
    @event_datetime = @event.datetime.to_s(:short).in_time_zone('Tehran').to_s
    @event_datetime = @event_datetime.to_persian
    @event_datetime.gsub!("-", "/")
    @event_datetime.gsub!(" ", " -  ")
    @event_datetime = @event_datetime.split(":")[0..1].join(":")
  end

  def feed
    @title = t(:future_events)
    @future_events = Event.future.limit(20)
    @updated = @future_events.last.updated_at unless @future_events.empty?

    respond_to do |f|
      f.atom { render :layout => false }
      f.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
    end
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController

  def index
    @albums = Album.all
  end

  def pictures(album_id)
  end

  def videos(album_id)
  end

  def docs(album_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'date'
    require 'persian_string'

    @user = User.new
    # nearest_event
    @event = Event.future.first
    if @event
      @days = (Date.new(@event.datetime.year,
                        @event.datetime.month,
                        @event.datetime.day)- Date.today).to_i
      if @days < 0
        @days = "0"
      end
      @days = @days.to_s.to_persian
    else
      @days = "0".to_persian
    end

    @future_events = Event.order("datetime ASC").future.limit(10)
    @past_events = Event.order("datetime ASC").past.limit(10).reverse
    @loc = I18n.default_locale
    flash = {}
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_filter :setup_negative_captcha, :only => [:new, :create]

  def new
    @participant = Participant.new
    @event = Event.find(params[:id])
    if @event.is_full?
      redirect_to :event_is_full
    end
  end

  def create
    @event = Event.find(params[:id])
    if @event.is_full?
      redirect_to :event_is_full
    end

    @participant = Participant.new(@captcha.values)
    @participant.event = @event
    if @captcha.valid? and @participant.save
      flash[:success] = t("You registered to this event")
      @event.capacity -= 1
      @event.save
      redirect_to root_path
    else
      flash[:error] = @captcha.error if @captcha.error
      render :action => 'new'
    end
  end

  private
  def resource_params
    params.require("participant").permit(:first_name, :last_name,
                                         :email, :cell_phone)
  end

  def setup_negative_captcha
    # A secret key entered in environment.rb. 'rake secret' will give you a good one.
    @captcha = NegativeCaptcha.new(secret: NEGATIVE_CAPTCHA_SECRET,
                                   spinner: request.remote_ip,
                                   # Whatever fields are in your form
                                   fields: [:first_name,
                                            :last_name,
                                            :email,
                                            :cell_phone],
                                   params: params)
  end
end

app/controllers/users_controller.rb
require 'mailing_list'

class UsersController < ApplicationController

  def create
    user = User.new(params.require(:user).permit(:email))

    if user.save
      flash[:success] = t(:success)
      ML.add_user(user)
    else
      flash[:error] = t(:error)
    end
    redirect_to root_url

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/full.html.erb
<section class="middle">
  <h1><i class="icon icon-exclamation-sign"></i> <%=t :event_is_full %></h1>
  <br />
  <div class="err_details"><span><%=t :full_event_note %></span></div>
  <br /><br />
  <a href="/" class="btn"><%=t :back %></a>
</section>

app/views/events/index.html.erb
<section class="sponsors" id="events">
<div class="container">
  <div class="row">
    <div class="span6 event-list">
      <h1 class="text-center"><%=t :future_events %></h1>
      <% if @future_events.count > 0 %>
        <ul>
          <% @future_events.each do |event| %>
            <li>[<%= event.datetime.strftime("%Y/%m/%d") %>] <a href="<%= event_path(event) %>"><%= event.name %></a></li>
          <% end %>
        </ul>
      <% else %>
        <p><%=t :no_event %>
      <% end %>
    </div>
    <div class="span6 event-list">
      <h1 class="text-center"><%=t :past_events %></h1>
      <% if @past_events.count > 0 %>
        <ul>
          <% @past_events.each do |event| %>
            <li>[<%= event.datetime.strftime("%Y/%m/%d") %>] <a href="<%= event_path(event) %>"><%= event.name %></a></li>
          <% end %>
        </ul>
      <% else %>
        <p><%=t :no_event %></p>
      <% end %>
    </div>
  </div>
</div>
</section>

app/views/events/show.html.erb
<% content_for :header do %>
  <meta name="twitter:card" content="summary">
  <meta name="twitter:creator" content="@karajlug">
  <meta name="description" content="<%=t :karaj_lug_running_sfd %>: <%= @event.name %>">
  <meta name="twitter:url" content="<%= event_url(@event) %>">
  <meta name="twitter:title" content="<%= @event.name %>">
  <meta name="twitter:description" content="<%= @event.description.gsub("\n", "<br/>") %>">
<% end %>

<section id="last-event">
  <div class="content">
    <div class="row">
      <div class="span10 offset2 event">
        <div class="row">
          <div class="span7">
            <h2><%= @event.name %></h2><% if @event.finished? %><span class="label label-success"><i class="icon icon-check 2x"></i> <%=t :been_held %></span><% end %>
          </div>
          <div class="span3 text-right buttons">
            <br />
            <% if @event.finished? %>
              <a href=<% if not @event.image_album_url.empty? %>"<%= @event.image_album_url %>"<% else %>"#"<% end %> class="btn btn-info <% if @event.image_album_url.empty? %>disabled<% end %>"><i class="icon icon-camera"></i> <%=t :images %></a>
              <a href=<% if not @event.video_album_url.empty? %>"<%= @event.video_album_url %>"<% else %>"#"<% end %> class="btn btn-success <% if @event.video_album_url.empty? %>disabled<% end %>"><i class="icon icon-film"></i> <%=t :videos %></a>
            <% elsif @event.need_registration %>
              <a href="/events/<%= @event.id %>/register" class="btn btn-inverse icon-large float-left"><%=t :register_now %></a>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="span5 desc float-right"><p><%= @event.description.gsub("\n", "<br/>").html_safe %></p></div>
          <div class="span5 float-left desc">
            <p><span><%=t :address %>:<br /><br /> <span><%= @event.address %></span></span></p>
          </div>
        </div>
        <div class="row">
          <span class="span3 timestamp"><i class="icon icon-time"></i> <span class="green" dir="<%= @reverse_dir %>"><%= @event_datetime %></span></span>
          <div class="span3 offset4 float-left text-left share_it">
            <span><%=t :share_it %>:</span>
            <a href="https://twitter.com/share?via=karajlug&text=<%= URI.escape(@event.name) %>&url=<%= URI.escape(event_url(@event)) %>"><i class="icon icon-twitter icon-large"></i></a> |
            <a href="http://www.facebook.com/sharer.php?u=<%= URI.escape(event_url(@event)) %>&t=<%= URI.escape(@event.name) %>"><i class="icon icon-facebook icon-large"></i></a> |
            <a href="https://plus.google.com/share?url=<%= URI.escape(event_url(@event)) %>"><i class="icon icon-google-plus icon-large"></i></a>

          </div>
        </div>
        <br /><br />
        <% if not @event.resources.empty? %>
        <div class="row">
          <h2><%=t :resources %>:</h2>
          <ul>
            <% @event.resources.each do |resource| %>
              <li><a href="<%= resource.url %>"><%= resource.name %></a> - <%= resource.desc %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/gallery/index.html.erb
<%= stylesheet_link_tag    "fancybox", media: "all", "data-turbolinks-track" => true %>
<%= stylesheet_link_tag    "gallery", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "fancybox", "data-turbolinks-track" => true %>

<div class="gallery">
  <% @albums.each do |album| -%>
    <section class="<%= cycle("address", "sponsors", "green-pad", "sponsors") %>">

      <div class="album container">
        <div class="album_name">
          <h1><%= album.name %></h1>
        </div>
        <div class="album_menu">
              <% album.media.each do |x| %>
                <a class="fancybox" rel="fancybox-thumb" title="<%= x.desc %>" href="<%= x.file %>">
                  <%= image_tag x.file.url(:thumb), :class => "image-border" %>
                </a>
              <% end %>
        </div>
      </div>
    </section>
  <% end -%>
</div>

app/views/home/index.html.erb
<section class="address" id="last-event">
  <div class="container">
    <div class="row">
      <div class="row">
      <% flash.each do |key, value| %>
        <div id="alert" class="span10 offset1 alert alert-<%= key %>">
          <button type="button" class="close pull-left" data-dismiss="alert" onclick="$('#alert').fadeOut();">&times;</button>
          <%= value %>
        </div>
      <% end %>
      </div>
      <div class="span6">
        <div id="intro">
          <div class="logo"></div>
          <br>
          <h1><%=t :karaj_lug_running_sfd %></h1>
          <h3><%= @event.name if @event %></h3>
        </div>
      </div>
      <div class="span6">
        <div id="days">
          <h1><%= @days %></h1>
          <h2><%=t :ramaining_msg %></h2>
          <% if @event and @event.need_registration and not @event.finished? %><br />
            <a href="/events/<%= @event.id %>/register" class="btn btn-large btn-inverse"><%=t :register_now %></a>
          <% end %>
          <ul id="share_this" class="vertical">
            <li id="sharetext"><%=t :share %>:  </li>
            <li><a href="https://twitter.com/intent/tweet?source=KarajLug&amp;text=رویدادهای کرج لاگ&amp;url=http%3A//events.karajlug.org/"><i class="icon-twitter icon-large"></i></a></li>
            <li><a href="http://www.facebook.com/sharer.php?u=http%3A//events.karajlug.org/&amp;t=رویدادهای کرج لاگ"><i class="icon-facebook-sign icon-large"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="sponsors" id="events">
<div class="container">
  <div class="row">
    <div class="span6 event-list">
      <h1 class="text-center"><%=t :future_events %></h1>
      <% if @future_events.count > 0 %>
        <ul>
          <% @future_events.each do |event| %>
            <li>[<%= event.datetime.strftime("%Y/%m/%d") %>] <a href="<%= event_path(event) %>"><%= event.name %></a></li>
          <% end %>
        </ul>
      <% else %>
        <p><%=t :no_event %>
      <% end %>
    </div>
    <div class="span6 event-list">
      <h1 class="text-center"><%=t :past_events %></h1>
      <% if @past_events.count > 0 %>
        <ul>
          <% @past_events.each do |event| %>
            <li>[<%= event.datetime.strftime("%Y/%m/%d") %>] <a href="<%= event_path(event) %>"><%= event.name %></a></li>
          <% end %>
        </ul>
      <% else %>
        <p><%=t :no_event %></p>
      <% end %>
    </div>
  </div>
</div>
</section>

<section class="green-pad" id="i-want-to-participate">
  <div class="container">
    <h1><%=t :i_want_to_participate %></h1>

    <br><br>
    <%= form_for(@user) do |f| %>
            <div class="regform">
                <br><br>
                <div class="forminput">
                  <%= f.text_field :email, placeholder: t(:email) + " ...", id: :email %><br />
                  <span><%=t :form_msg %></span> <%= f.submit t(:submit), class: "btn btn-inverse", id: "submit" %>

                </div>
                <br><br>
            </div>
    <% end %>
        <div class="para">
          <p><%=t :join_the_team_html %></p>
        </div>
    </div>
</section>

<section class="sponsors" id="sponsors">
  <div class="container">
    <div class="row">
      <div class="span3 offset1">
        <h1><%=t :sponsors %>:</h1>
      </div>
    </div>
    <br /><br />

    <div class="row">

      <div class="span6 text-center" style="margin-top: 110px;">
        <a href="//yellowen.com" ><%= image_tag("yellowen.png") %></a>
      </div>

      <div class="span6 text-center" style="margin-top: 70px;">
        <a href="//karanic.com"><%= image_tag("karanic.png") %></a>
      </div>

    </div>

    <div class="row sponsorship">
      <div class="span6 offset3 text-center">
        <p>
          <%=t :sponsorship_html %>
        </p>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>" dir="rtl">
<head>

  <meta charset="UTF-8">

  <meta name="description" content="KarajLug Karaj Linux users group">
  <meta name="author" content="Sameer Rahmani - Behnam Ahmad Khan Beigi - Ebrahim Byagowi">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= yield :header %>
  <%= auto_discovery_link_tag :atom, "/feed" %>
  <%= auto_discovery_link_tag :rss, "/feed.rss" %>

  <title><%=t :site_title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <link rel="shortcut icon" href="<%= asset_path("favicon.png") %>">

  <style type="text/css">
      body{
          padding-top: 20px;
      }
  </style>

  <% if I18n.locale == :fa %>
  <%= stylesheet_link_tag    "style_rtl", media: "all", "data-turbolinks-track" => true %>
  <% else %>
  <%= stylesheet_link_tag    "style_ltr", media: "all", "data-turbolinks-track" => true %>
  <% end -%>

</head>
<body dir="<% if I18n.locale == :fa %>rtl<% else %>ltr<% end %>" id="sfd">

<div class="navbar navbar-fixed-top" data-spy="affix" data-offset-top="10">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="//karajlug.org"></a>
      <div class="nav-collapse collapse">
        <ul class="nav" id="topnav">
          <% if request.path == "/" %>
          <li><a href="#last-event"><%=t :last_event %></a></li>
          <li><a href="#events"><%=t :events %></a></li>
          <li><a href="#i-want-to-participate"><%=t :i_want_to_participate %></a></li>
          <li><a href="#sponsors"><%=t :sponsors %></a></li>
          <% else %>
          <li><a href="/"><%=t :home %></a></li>
          <% end %>
        </ul>
        <ul class="nav pull-left" id="socialicon">
          <li><a href="/feed"><i class="icon icon-rss"></i></a></li>
          <li><a href="https://www.twitter.com/karajlug"><i class="icon-twitter icon-large"></i></a></li>
          <li><a href="http://www.facebook.com/pages/KarajLug/113288182057531"><i class="icon-facebook-sign icon-large"></i></a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>


    <div class="maincontainer">
      <%= yield %>
    </div>

    <footer>
      © <%=t :copy_right_html %>
    </footer>

<script type="text/javascript">
    $('.nav li a').scrollTo();
    $.scrollUp({
        scrollText: ''
    });
</script>
<!-- Start of StatCounter Code for Default Guide -->
<script type="text/javascript">
  var sc_project=9541118;
  var sc_invisible=1;
  var sc_security="d432d299";
  var scJsHost = (("https:" == document.location.protocol) ?
  "https://secure." : "http://www.");
  document.write("<sc"+"ript type='text/javascript' src='" +
                                                          scJsHost+
                                                          "statcounter.com/counter/counter.js'></"+"script>");
</script>
<noscript><div class="statcounter"><a title="web stats"
                                      href="http://statcounter.com/free-web-stats/"
                                      target="_blank"><img class="statcounter"
                                                           src="http://c.statcounter.com/9541118/0/d432d299/1/"
                                                           alt="web stats"></a></div></noscript>
<!-- End of StatCounter Code for Default Guide -->
</body>
</html>

app/views/newsletter/send_newsletter.html.erb
Hi its a test

app/views/participants/_form.html.erb
<% if @participant.errors.any? %>
  <div  class="row">
    <div id="error_explanation" class="span10 offset1">
      <h2><%=t :please_fix_the_mistakes %></h2>

    </div>
  </div>
<% end %>

<div class="row">
  <%= form_for @participant, :url => "/events/#{@event.id}/register" do |f| %>
  <fieldset class="span10 offset1">
    <legend><%=t :registeration %></legend>
    <p><%=t :reg_details %></p>

    <%= raw negative_captcha(@captcha) %>
    <div class="row">
      <div class="field span5 <% if @participant.errors.include? :first_name %>has_error<% end %>">
        <%= negative_label_tag(@captcha, :first_name, t("first_name") + ":") %><br>
        <%= negative_text_field_tag(@captcha, :first_name) %>
        <% if @participant.errors.include? :first_name %>
          <span class="text-error"><%= @participant.errors[:first_name][0] %></span>
        <% end %>
      </div>
      <div class="field span4 <% if @participant.errors.include? :last_name %>has_error<% end %>">
        <%= negative_label_tag(@captcha, :last_name, t("last_name") + ":") %><br>
        <%= negative_text_field_tag(@captcha, :last_name) %>
        <% if @participant.errors.include? :last_name %>
          <span class="text-error"><%= @participant.errors[:last_name][0] %></span>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="field span5 <% if @participant.errors.include? :email %>has_error<% end %>">
        <%= negative_label_tag(@captcha, :email, t("email") + ":") %><br>
        <%= negative_text_field_tag(@captcha, :email) %>
        <% if @participant.errors.include? :email %>
          <span class="text-error"><%=t @participant.errors[:email][0] %></span>
        <% end %>

      </div>
      <div class="field span4 <% if @participant.errors.include? :cell_phone %>has_error<% end %>">
        <%= negative_label_tag(@captcha, :cell_phone, t("cell_phone") + ":") %><br>
        <%= negative_text_field_tag(@captcha, :cell_phone) %>
        <% if @participant.errors.include? :cell_phone %>
          <span class="text-error"><%= @participant.errors[:cell_phone][0] %></span>
        <% end %>
        <span class="desc"><%=t :cell_phone_description %></span>
      </div>
    </div>
    <div class="actions">
      <%= submit_tag t(:register), :class => "btn btn-success btn-large" %>
    </div>
  </fieldset>
<% end %>
</div>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<h1>Listing participants</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Cell phone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.first_name %></td>
        <td><%= participant.last_name %></td>
        <td><%= participant.email %></td>
        <td><%= participant.cell_phone %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<div class="container">
  <div class="row">
    <%= render 'form' %>
  </div>
</div>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @participant.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @participant.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @participant.email %>
</p>

<p>
  <strong>Cell phone:</strong>
  <%= @participant.cell_phone %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>

app/views/users/index.html.erb
<section class="address">
  <div class="container">
    <div class="row">
      <div class="span6">
        <div id="intro">
          <div class="logo"></div>
          <br>
          <h1><%=t :karaj_lug_running_sfd %></h1>
          <h3><%=t :sfd_2013_celebration %></h3>
        </div>
      </div>
      <div class="span6">
        <div id="days">
          <h1><%= @days %></h1>
          <h2><%=t :ramaining_msg %></h2>
          <ul id="share_this" class="vertical">
            <li id="sharetext"><%=t :share %>:  </li>
            <li><a href="https://twitter.com/intent/tweet?source=KarajLug&amp;text=جشن روز آزادی نرم افزار ۲۰۱۳&amp;url=http%3A//sfd.karajlug.org/"><i class="icon-twitter icon-large"></i></a></li>
            <li><a href="http://www.facebook.com/sharer.php?u=http%3A//sfd.karajlug.org/&amp;t=جشن روز آزادی نرم افزار ۲۰۱۳"><i class="icon-facebook-sign icon-large"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="sponsors" id="what-is-sfd">
<div class="container">
  <div class="row">
    <div class="span12">
      <h1><%=t :what_is_sfd %></h1>
      <p class="big-text what-is-sfd"><%=t :sfd_is_html %></p>
    </div>
  </div>
</div>
</section>

<section class="green-pad" id="i-want-to-participate">
  <div class="container">
    <h1><%=t :i_want_to_participate %></h1>

    <br><br>
    <%= form_for(@user) do |f| %>
            <div class="regform">
                <br><br>
                <div class="forminput">
                  <% flash.each do |key, value| %>
                      <div id="alert" class="alert alert-<%= key %>">
                        <button type="button" class="close pull-left" data-dismiss="alert" onclick="$('#alert').fadeOut();">&times;</button>
                        <%= value %>
                      </div>
                  <% end %>

                  <%= f.text_field :email, placeholder: t(:email) + " ...", id: :email %><br />
                  <span><%=t :form_msg %></span> <%= f.submit t(:submit), class: "btn btn-inverse", id: "submit" %>

                </div>
                <br><br>
            </div>
    <% end %>
        <div class="para">
          <p><%=t :join_the_team_html %></p>
        </div>
    </div>
</section>

<section class="sponsors" id="sponsors">
  <div class="container">
    <h1><%=t :sponsors %>:</h1>

    <div class="row">

      <div class="span3 text-center">
        <a href="//karaj.ir"><%= image_tag("muni.png") %></a>
      </div>
      <div class="span4 text-center" style="margin-top: 50px;">
        <a href="//karanic.com"><%= image_tag("karanic.png") %></a>
      </div>
      <div class="span4 text-center" style="margin-top: 110px;">
        <a href="//yellowen.com" ><%= image_tag("yellowen.png") %></a>
      </div>


    </div>

  </div>
  <div class="clearfix"></div>
</section>